### ISSUE TITLE
Specific failing analyses

### ISSUE THREAD

**Issue by dhimmel** [idrdex/star_api#13]
Using the current version of this package (idrdex/star_api@cf6d20c6e1a2476e25f2f69767eafb61ab55a8f0), I ran analyses for my disease list.

[Here are the 17 queries](https://github.com/dhimmel/stargeo/blob/1899b6b59facaf4fac56b3a3af9992fe813b9f4c/data/errors.csv) that resulted in errors.

The majority of failures were due to:
- either `'Int64Index' object has no attribute 'labels'`
- or `zero-size array to reduction operation maximum which has no identity` (potentially related to #5)

@idrdex, can you look into these errors? Merry christmas, hope this is a suitable gift (-;

**Comment by dhimmel** [comment]
Thanks @idrdex for the latest update (f27e37b2df0414601b0f119a61b99e8c68fb204f). It resolved 11 of 17 failing analyses and introduced [3 new](https://github.com/dhimmel/stargeo/commit/f32a4bfeb8ea36dd4f464dcda334d72022ff4600#diff-640261949c9679580d63d2c1304d3230) failures.

 There are still [9 failures](https://github.com/dhimmel/stargeo/blob/f32a4bfeb8ea36dd4f464dcda334d72022ff4600/data/errors.csv).

Six of the remaining failures are `'Int64Index' object has no attribute 'labels'` Here's the [log for nicotine dependence](https://github.com/dhimmel/stargeo/blob/f32a4bfeb8ea36dd4f464dcda334d72022ff4600/data/doslim/DOID_0050742/log.txt) (smoker versus non-smoker), which failed with this error.

**Comment by dhimmel** [comment]
I updated [three of my tags](https://github.com/dhimmel/stargeo/commit/ae1f20b131e6d1c43c77f7181429aa182e546f7d?diff=unified) that were outdated. This solved two of the errors.

Of the remaining [7 errors](https://github.com/dhimmel/stargeo/blob/b9e7a5c26bd9906353ac939b31486c877be1baa2/data/errors.csv), 4 are `'Int64Index' object has no attribute 'labels'`.

**Comment by iDrDex** [comment]
Bladder_cancer and bladder_cancer_control were renamed to bladder_cancer_tissue and bladder_cancer_tissue_control.  I updated the tag names to be consistent and it works now.

**Comment by Suor** [comment]
Looked into all of these. Fixed by skipping bad or absent data or just improving error messages.

**mygene_sym**

This line skips all the data, so meta-analysis result is empty:

``` python
if len(gene_fold_change) == 1:
    continue
```

**'Int64Index' object has no attribute 'labels'**

df is empty, error in checking it, fixed.

**zero-size array to reduction operation maximum which has no identity**

GSE43076-GPL6480_series_matrix.txt.gz has no gene data, this lead to error, skip it now.

**Can't find matrix file for ...**

No series matrix file on ftp, changed behavior to just skip it. 
Analysis is now run on the rest of data.

**Comment by dhimmel** [comment]
Okay all of our analyses now complete error free ([commit](https://github.com/dhimmel/stargeo/commit/1718c96ff70eaddafb20ae942ae5d18181195c58))!

Thanks @Suor and @idrdex for all the help.

**Comment by iDrDex** [comment]
Thx @dhimmel. @Suor can you set up via: https://github.com/idrdex/star_api the ability to programmatically run these analyses.  Ultimately we should have them show up on our list of run analyses: http://stargeo.org/analysis/

**Comment by Suor** [comment]
@idrdex do you want to also run permutations on stargeo.org?

**Comment by iDrDex** [comment]
Probably not for now. People can run those locally.

**Comment by Suor** [comment]
Created and had issues https://github.com/idrdex/star-django/issues/36 and https://github.com/idrdex/star-django/issues/22 for this. Also created sharing code issue here - https://github.com/idrdex/star_api/issues/17.

Closing this as analyses are not failing.
