### ISSUE TITLE
Interpreting `random_TE` and `fixed_TE`

### ISSUE THREAD

**Issue by dhimmel** [idrdex/star_api#16]
I assume  `random_TE` and `fixed_TE` refer to the estimated effect size from random and fixed effects meta-analyses. What type of effect sizes are they? For example, are they `log2(fold_change)` or the coefficient of a logistic regression model (so log-odds-ratios)?

**Comment by iDrDex** [comment]
lof2 fold change.  Here’s the r package I mimicked: https://cran.r-project.org/web/packages/meta/index.html https://cran.r-project.org/web/packages/meta/index.html.  metacon is the specific function.  all the abbreviations are descried there.
