### ISSUE TITLE
Failing analyses

### ISSUE THREAD

**Issue by dhimmel** [idrdex/star_api#3]
I've attempted a first pass at the analyses.

[This table](https://github.com/dhimmel/star_api/blob/f627676993e5db1db53b3f37490bd40c6f964d9f/data/files.tsv) shows whether a query created output files for logging, samples, and meta-analyses. The queries where `samples.tsv == False` are failing due to an exception.

@idrdex, can you see if you can get any of the `samples.tsv == False` queries to execute?

**Comment by dhimmel** [comment]
Verifying that the analyses fail when doing a web analysis. See [the log](http://dev.stargeo.io/analysis/242/log/) for prostate cancer. The error is:

```
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by idrdex** [comment]
Let's fix next week? Halloween is a big deal in my household :)

dex*
